import 'custom-tabs/custom-tabs.js'
import './../node_modules/custom-pages/src/custom-pages.js'
import './translated-tab'
import './summary-panel.js'
import './summary-panel-mirror.js'
import './top-box.js'
